apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: node-web-app-source
  namespace: node-web-project
spec:
  params:
    - name: url
      value: 'https://github.com/RolandOrg/node-web-app.git'
    - name: revision
      value: master
  type: git
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: node-web-app-image
  namespace: node-web-project
spec:
  params:
    - name: url
      value: 'image-registry.openshift-image-registry.svc:5000/node-web-project/web-node-app:v1.0.5'
  type: image
