apiVersion: tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: node-web-app-tt
spec:
  resourcetemplates:
  - apiVersion: tekton.dev/v1alpha1
    kind: PipelineResource
    metadata:
      name: node-web-app-source-dynamic
      namespace: node-web-project
    spec:
      params:
      - name: url
        value: ${params.git-repo-url}
      - name: revision
        value: ${params.git-revision}
    type: git
  - apiVersion: tekton.dev/v1alpha1
    kind: PipelineResource
    metadata:
      name: node-web-app-image-dynamic
      namespace: node-web-project
    spec:
      params:
      - name: url
        value: 'image-registry.openshift-image-registry.svc:5000/node-web-project/web-node-app:(params.git-revision)'
    type: image
  - apiVersion: tekton.dev/v1alpha1
    kind: PipelineRun
    metadata:
      generateName: node-web-app-pipeline-run-
      namespace: node-web-project
    spec:
      pipelineRef:
        name: node-web-app-pipeline
      resources:
      - name: node-web-app-source
        resourceRef:
          name: node-web-app-source-dynamic
      - name: node-web-app-image
        resourceRef:
          name: node-web-app-image-dynamic
      serviceAccountName: pipeline


--- 

apiVersion: tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: node-web-app-tb
spec:
  params:
  - name: git-repo-url
    value: $(body.repository.url)
  - name: git-revision
    value: $(body.head_commit.id)

---

apiVersion: tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: node-web-app-el
spec:
  serviceAccountName: pipeline
  triggers:
  - bindings:
    - name: node-web-app-tb
    template:
      name: node-web-app-tt

---

apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: el-node-web-app
  namespace: node-web-project
spec:
  host: el-node-web-app.apps.roly-ocp43-cluster.roly-ocp.com
  to:
    kind: Service
    name: el-node-web-app-el
    weight: 100