apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: node-web-app-pipeline
  namespace: node-web-project
spec:
  resources:
    - name: default-node-web-app-source
      type: git
    - name: default-node-web-app-image
      type: image
  tasks:
    - name: build-and-publish-image
      params:
        - name: BUILDER_IMAGE
          value: 'quay.io/buildah/stable:v1.11.0'
        - name: DOCKERFILE
          value: ./Dockerfile
        - name: TLSVERIFY
          value: 'false'
      resources:
        inputs:
          - name: source
            resource: default-node-web-app-source
        outputs:
          - name: image
            resource: default-node-web-app-image
      taskRef:
        kind: ClusterTask
        name: buildah
    - name: argocd-sync-deployment
      params:
        - name: application-name
          value: node-web-app
        - name: flags
          value: '--insecure'
        - name: argocd-version
          value: v1.4.2
      runAfter:
        - build-and-publish-image
      taskRef:
        kind: Task
        name: argocd-task-sync-and-wait